/**
 * BrainVault — Memory Routes
 *
 * POST /api/memory/add   — Ingest a new memory (text or audio file)
 * POST /api/memory/query — Query stored memories with natural language
 */

const express = require('express');
const multer = require('multer');
const {
  extractMemoryFromText,
  extractMemoryFromAudio,
  generateEmbedding,
  synthesizeAnswer,
} = require('../services/gemini');
const { insertMemory, hybridSearch } = require('../services/database');

const router = express.Router();

// ─────────────────────────────────────────────────────────────────────────────
// Multer Configuration (Audio File Upload)
// ─────────────────────────────────────────────────────────────────────────────

// Store uploaded audio files in memory (Buffer) — no disk needed
// 10 MB limit is generous for voice memos (1 min M4A ≈ 500 KB)
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    // Accept common audio MIME types that Gemini supports
    const allowedTypes = [
      'audio/mp4',       // M4A container
      'audio/x-m4a',     // M4A alternate MIME
      'audio/m4a',       // M4A alternate MIME
      'audio/mpeg',      // MP3
      'audio/wav',       // WAV
      'audio/x-wav',     // WAV alternate MIME
      'audio/webm',      // WebM audio
      'audio/ogg',       // OGG audio
      'audio/aac',       // Raw AAC
    ];

    const isAllowedMime = allowedTypes.includes(file.mimetype);

    // Fallback: If generic mimetype, check file extension
    let isAllowedExtension = false;
    if (!isAllowedMime && file.mimetype === 'application/octet-stream') {
      const ext = file.originalname.split('.').pop().toLowerCase();
      const extToMime = {
        'm4a': 'audio/m4a',
        'mp3': 'audio/mpeg',
        'wav': 'audio/wav',
        'webm': 'audio/webm',
        'ogg': 'audio/ogg',
        'aac': 'audio/aac'
      };
      
      if (extToMime[ext]) {
        file.mimetype = extToMime[ext]; // Normalize the mimetype for Gemini
        isAllowedExtension = true;
      }
    }

    if (isAllowedMime || isAllowedExtension) {
      cb(null, true);
    } else {
      cb(new Error(`Unsupported audio format: ${file.mimetype}. Accepted: M4A, MP3, WAV, WebM, OGG`));
    }
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/memory/add
// ─────────────────────────────────────────────────────────────────────────────
//
// Accepts multipart/form-data with either:
//   - A "text" field (string) — for typed text memories
//   - An "audio" file field — for recorded audio memories
//
// Flow:
//   1. Validate input (text xor audio)
//   2. Send to Gemini for structured extraction
//   3. Generate 768-dim embedding
//   4. Persist to Supabase
//   5. Return saved memory metadata
// ─────────────────────────────────────────────────────────────────────────────

router.post('/add', upload.single('audio'), async (req, res) => {
  try {
    const textInput = req.body?.text?.trim();
    const audioFile = req.file;

    // Must provide either text or audio, not both empty
    if (!textInput && !audioFile) {
      return res.status(400).json({
        error: 'Please provide either a text memory or an audio recording.',
      });
    }

    // Use server's current date for relative date interpretation by the LLM
    const currentDate = new Date().toISOString().split('T')[0]; // YYYY-MM-DD

    let extraction;
    let rawText;
    let sourceType;

    if (audioFile) {
      // ── Audio ingestion path ──────────────────────────────────────────
      sourceType = 'audio';
      console.log(`[ADD] Processing audio: ${audioFile.originalname} (${audioFile.mimetype}, ${audioFile.size} bytes)`);

      extraction = await extractMemoryFromAudio(
        audioFile.buffer,
        audioFile.mimetype,
        currentDate
      );
      // Use the verbatim transcript generated by the LLM as the raw text
      rawText = extraction.raw_transcript || extraction.cleaned_text;
    } else {
      // ── Text ingestion path ───────────────────────────────────────────
      sourceType = 'text';
      rawText = textInput;
      console.log(`[ADD] Processing text: "${textInput.substring(0, 80)}..."`);

      extraction = await extractMemoryFromText(textInput, currentDate);
    }

    // Generate semantic embedding from the cleaned text
    const embedding = await generateEmbedding(extraction.cleaned_text);

    // Persist the complete memory record to the database
    const savedMemory = await insertMemory({
      ...extraction,
      raw_text: rawText,
      source_type: sourceType,
      embedding,
    });

    console.log(`[ADD] Memory saved: ${savedMemory.id} (${sourceType}, subject: ${savedMemory.subject})`);

    return res.status(201).json({
      success: true,
      memory: savedMemory,
    });
  } catch (err) {
    console.error('[ADD] Error:', err.message);
    return res.status(500).json({ error: err.message });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/memory/query
// ─────────────────────────────────────────────────────────────────────────────
//
// Body: { "question": "When did I run my first marathon?" }
//
// Flow:
//   1. Generate embedding for the question
//   2. Hybrid search (vector + keyword) against the DB
//   3. Pass matched memories as context to Gemini
//   4. Return synthesized answer + source references
// ─────────────────────────────────────────────────────────────────────────────

router.post('/query', async (req, res) => {
  try {
    const { question } = req.body;

    if (!question?.trim()) {
      return res.status(400).json({
        error: 'Please provide a question.',
      });
    }

    const trimmedQuestion = question.trim();
    console.log(`[QUERY] "${trimmedQuestion}"`);

    // Step 1: Embed the question for semantic search
    const queryEmbedding = await generateEmbedding(trimmedQuestion);

    // Step 2: Hybrid search — semantic + keyword, top 5 results
    const matches = await hybridSearch(queryEmbedding, trimmedQuestion, 5);

    // Step 3: Handle empty results
    if (matches.length === 0) {
      return res.json({
        answer:
          "I don't have any memories that match your question yet. " +
          'Try adding some memories first!',
        sources: [],
      });
    }

    // Step 4: Synthesize a natural language answer from context
    const answer = await synthesizeAnswer(trimmedQuestion, matches);

    // Step 5: Format source references for the client
    const sources = matches.map((m) => ({
      id: m.id,
      event_date: m.event_date,
      subject: m.subject,
      tags: m.tags,
      summary: m.cleaned_text,
      relevance: Math.round((m.similarity_score || 0) * 100),
    }));

    console.log(`[QUERY] Answered with ${sources.length} source(s)`);

    return res.json({ answer, sources });
  } catch (err) {
    console.error('[QUERY] Error:', err.message);
    return res.status(500).json({ error: err.message });
  }
});

module.exports = router;
